# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 07:00
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('baseuser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.BaseUser')),
                ('invisible', models.ManyToManyField(default=None, related_name='invisible', to='core.BaseUser')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated1', models.DateTimeField()),
                ('updated2', models.DateTimeField()),
                ('baseuser1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='baseuser1', to='core.BaseUser')),
                ('baseuser2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='baseuser2', to='core.BaseUser')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('scope', models.CharField(choices=[('Public', 'Public'), ('Friends Only', 'Friends Only'), ('Private', 'Private'), ('Hidden', 'Hidden')], max_length=13)),
                ('feedtype', models.CharField(choices=[('Text', 'Text'), ('Markdown', 'Markdown')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseUser')),
                ('dislike', models.ManyToManyField(default=None, related_name='disliked', to='core.BaseUser')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseuser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='baseuser', to='core.BaseUser')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='core.BaseUser')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isMafiaRoom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('baseuser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.BaseUser')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.upload_path)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseUser')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Feed')),
            ],
        ),
        migrations.AddField(
            model_name='multichatroom',
            name='users',
            field=models.ManyToManyField(default=None, related_name='users', to='core.MultiChatUser'),
        ),
        migrations.AddField(
            model_name='feed',
            name='hashtag',
            field=models.ManyToManyField(default=None, related_name='hashtags', to='core.HashTag'),
        ),
        migrations.AddField(
            model_name='feed',
            name='like',
            field=models.ManyToManyField(default=None, related_name='liked', to='core.BaseUser'),
        ),
        migrations.AddField(
            model_name='chat',
            name='multiroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MultiChatRoom'),
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ChatRoom'),
        ),
    ]
