# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RoomUser',
            new_name='MultiChatUser',
        ),
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ChatRoom'),
        ),
        migrations.AddField(
            model_name='multichatroom',
            name='users',
            field=models.ManyToManyField(default=None, related_name='users', to='core.MultiChatUser'),
        ),
        migrations.AddField(
            model_name='chat',
            name='multiroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.MultiChatRoom'),
        ),
    ]
