# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170604_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='multiroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MultiChatRoom'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ChatRoom'),
        ),
    ]
