# Generated by Django 2.0.dev20170518171123 on 2017-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170604_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichatroom',
            name='isMafiaRoom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtagName',
            field=models.CharField(max_length=30),
        ),
    ]
