# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170514_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
